import React, { useState, useEffect } from 'react';
import { api } from '../api/client';
import { MapPin, Users, Sparkles, Calendar, Target, RefreshCw } from 'lucide-react';
import ScoreGauge from '../components/ScoreGauge';
import { renderFormattedText } from '../components/FormattedText';

export default function MarketIntel() {
  const [intel, setIntel] = useState(null);
  const [loading, setLoading] = useState(true);

  const loadIntel = async () => {
    setLoading(true);
    try {
      const data = await api.getMarketIntelligence();
      setIntel(data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadIntel();
  }, []);

  if (loading) {
    return (
      <div style={{ padding: '3rem', textAlign: 'center', color: 'var(--text-muted)' }}>
        <RefreshCw className="animate-spin" size={32} style={{ margin: '0 auto 1rem', color: 'var(--primary)' }} />
        <p>Analyzing Neighborhood Demographics & Locality Market Opportunities...</p>
      </div>
    );
  }

  const recs = intel?.recommendations || [];
  const highDemand = intel?.high_demand_categories || [];

  return (
    <div>
      <div className="section-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
        <div>
          <h1 className="section-title">AI-Powered Market Intelligence</h1>
          <p className="section-subtitle">Hyper-local market insights combining business profile, nearby institutions, and competitor density</p>
        </div>
        <button onClick={loadIntel} className="btn btn-secondary" style={{ padding: '0.5rem 1rem' }}>
          <RefreshCw size={16} /> Re-analyze Locality
        </button>
      </div>

      <div className="grid-2" style={{ marginBottom: '2rem' }}>
        {/* Core Locality AI Insight */}
        <div className="glass-card" style={{ padding: '1.75rem', borderLeft: '4px solid var(--primary)' }}>
          <div className="badge badge-info" style={{ marginBottom: '1rem' }}>
            <Sparkles size={14} /> Unique Locality Market Insight
          </div>
          <h2 style={{ fontSize: '1.25rem', lineHeight: 1.5, color: '#FFFFFF', marginBottom: '1rem' }}>
            "{renderFormattedText(intel?.ai_insight)}"
          </h2>
          <p style={{ fontSize: '0.875rem', color: 'var(--text-muted)' }}>
            Generated by synthesizing store location, nearby schools/colleges, offices, and population density.
          </p>
        </div>

        {/* Market Opportunity Score & Demand Categories */}
        <div className="glass-card" style={{ padding: '1.75rem', display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
          <div>
            <ScoreGauge 
              label="Market Opportunity Score"
              score={intel?.market_opportunity_score || 88.0}
              color="var(--primary)"
              subtitle="Untapped revenue potential in your immediate 2km radius"
            />

            <div style={{ marginTop: '1.25rem' }}>
              <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '0.5rem' }}>🔥 High Demand Categories in Your Locality:</div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem' }}>
                {highDemand.map((cat, i) => (
                  <span key={i} className="badge badge-success" style={{ padding: '0.4rem 0.75rem' }}>{cat}</span>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Strategic Market Recommendations */}
      <h2 style={{ fontSize: '1.2rem', marginBottom: '1.25rem', color: '#FFFFFF' }}>Strategic Growth Recommendations</h2>
      <div className="grid-3">
        {recs.map((rec, idx) => (
          <div key={idx} className="glass-card" style={{ padding: '1.5rem', display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.75rem' }}>
                <span className="badge badge-info">{rec.category}</span>
                <span className={`badge ${rec.impact_level === 'High' ? 'badge-success' : 'badge-warning'}`}>
                  {rec.impact_level} Impact
                </span>
              </div>

              <h3 style={{ fontSize: '1.1rem', marginBottom: '0.6rem', color: '#FFFFFF' }}>{rec.title}</h3>
              <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '1rem', lineHeight: 1.5 }}>
                {renderFormattedText(rec.description)}
              </p>
            </div>

            {rec.action_item && (
              <div style={{ padding: '0.75rem', background: 'rgba(6, 182, 212, 0.08)', borderRadius: 'var(--radius-sm)', border: '1px dashed var(--primary-glow)' }}>
                <strong style={{ fontSize: '0.8rem', color: 'var(--primary)', display: 'block', marginBottom: '0.2rem' }}>🎯 Recommended Action Item:</strong>
                <span style={{ fontSize: '0.85rem', color: 'var(--text-main)' }}>{renderFormattedText(rec.action_item)}</span>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
